//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongNo
    {
        public string Ma { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string SoTien { get; set; }
        public string DaTra { get; set; }
        public string ConLai { get; set; }
        public string MaNCC { get; set; }
        public string MaKH { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
